# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
sudo: required

language: go

rvm:
  - 2.3

services:
  - docker

env:
  - TERRAFORM_VERSION=0.11.3 IMAGE_NAME=azure-compute-module

jobs:
  include:
    - stage: go test
      install: true
      script:
      - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${IMAGE_NAME} .
      - docker run ${IMAGE_NAME} bash -c "export GOPATH=$HOME/terratest && export PATH=$PATH:/usr/local/go/bin && cd terratest/ssh && go test -args azureuser $HOME/.ssh/id_rsa"
